# .github/release-drafter.yml
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
      - "refactor"
  - title: "🔧 Dependencies"
    labels:
      - "dependencies"
      - "deps"
      - "dependency"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "chore"
      - "documentation"
      - "dependencies"
  default: patch

template: |
  ## What's Changed in $RESOLVED_VERSION

  $CHANGES

  ## Installation

  ```
  go install github.com/user/agent-def/cmd/agent-def@$RESOLVED_VERSION
  ```

  Or download the binary for your platform from the assets below.

  ## Full Changelog

  https://github.com/user/agent-def/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
