# .goreleaser.yml
# GoReleaser configuration for agent-sync

# Build configuration
builds:
  - id: agent-sync
    main: ./cmd/agent-sync/main.go
    binary: agent-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: agent-sync
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - docs/*

# Checksum configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshot configuration
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

# Release configuration
release:
  github:
    owner: uphy
    name: agent-sync
  prerelease: auto
  draft: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"

# Homebrew configuration
brews:
  - name: agent-sync
    repository:
      owner: uphy
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Convert context and command definitions for various AI agents"
    homepage: "https://github.com/uphy/agent-sync"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "agent-sync"
    test: |
      system "#{bin}/agent-sync --version"
