[tools]
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "v2.2.2"

[tasks.test]
run = "go test -timeout 30s ./..."

[tasks.integration-test]
run = "go test -timeout 30s -run ^TestAgentDef$"
dir = "internal/cli"
alias = "it"

[tasks.integration-test-replace]
run = "AGENT_DEF_REPLACE=true go test -timeout 30s -run ^TestAgentDef$"
dir = "internal/cli"
alias = "itr"

[tasks.dev]
run = "go run ./cmd/agent-def"
alias = "d"

[tasks.install]
run = "go install ./cmd/agent-def"
alias = "deploy"

[tasks.agent-def]
run = "go run ./cmd/agent-def build -f -c .agent-def/agent-def.yml"

[tasks.lint]
run = "golangci-lint run ./..."
alias = "l"

[tasks.format]
run = "gofmt -w ."

[tasks.build]
run = "go build ./..."

[tasks.pre-commit]
depends = ["build", "lint", "format", "test", "agent-def"]
