[tasks.integration-test]
run = "go test -timeout 30s -run ^TestAgentDef$"
dir = "internal/cli"
alias = "it"

[tasks.integration-test-replace]
run = "AGENT_DEF_REPLACE=true go test -timeout 30s -run ^TestAgentDef$"
dir = "internal/cli"
alias = "itr"

[tasks.install]
run = "go install ./cmd/agent-def"
alias = "deploy"

[tasks.agent-def]
run = "agent-def build -f"
dir = ".agent-def"