name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # Required for creating releases
  packages: write # Required for pushing to GitHub Packages if needed

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GoReleaser to generate proper changelogs

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          # This token is automatically provided by GitHub Actions
          # It needs to have permissions to push to the Homebrew tap repository
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      # If you need to create/validate a checksum file
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: agent-def-binaries
          path: dist/*
          if-no-files-found: error
